* features
- [X] variables
  - [X] getvar
  - [X] setvar
- [-] effects
  - [ ] reverb
  - [X] delay
  - [ ] filter
- [-] more complex oscillator
  - [X] types (saw, sqr, etc.)
    - [X] non-numeric values (drop down menu, in particular)
  - [ ] wave table?
- [ ] samples
- [-] array values
  - [X] make them show the length of the array
  - [X] see if they can be made temporally consistent. maybe not.
  - [X] do it so they can have easier editing
  - [ ] the current "step sequencer" should really be replaced with a "piano roll"
    - [ ] piano roll
      how would this even work? in particular, currently each component outputs a signal = an array of values, one value per time. perhaps the piano roll sits outside a synth plugin and triggers the synth accordingly.
      in order to do this, we'll need some notion of an instrument -- a factory for creating synth + envelope pairs.
- [X] arithmetic node
- [X] random values
- [ ] encapsulation
- [-] save/load
  - [X] serialization
  - [ ] write out, read in
- [ ] share on the net
* gui editor 
it's not so bad right now to edit the xml directly, but a gui editor is of course the goal.
- [X] done!
